### ISSUE TITLE
Saludos al iniciar el SDK sale esto

### ISSUE THREAD

**Issue by fecrono** [AndresRamos/Contpaqi#1]
Hola al inicializar el SDK me sale este error.

Información adicional: No se puede encontrar el punto de entrada denominado 'fSetNombrePAQ' en el archivo DLL 'MGWServicios.dll'.

Como puedo resolverlo?
Muchas gracias, excelente trabajo esta libreria!

**Comment by fecrono** [comment]
Ya encontre el error, el problema esta en el archivo: InicializacionAdminpaqSdk.cs  ahi debe usarse el nombre de AdminpaqSdk.fSetNombrePAQ para colocar el nombre correcto del programa, que en mi caso estoy usando AdminPAQ

**Comment by AndresRamos** [comment]
Hola! Ya corregi el error y actualize la libreria. Estaba utilizando el SDK de Adminpaq y no el de Comercial.
