### ISSUE TITLE
Código de error 139002 al insertar documento

### ISSUE THREAD

**Issue by hdz1javier2** [AndresRamos/Contpaqi#12]
Hola, intento insertar un documento de venta en Compaqi comercial y al ejecutar la función fAltaDocumento del SDK recibo el error 139002 con la descripción "La contraseña es incorrecta, favor de intentarlo nuevamente". A que contraseña se refiere? como y en que momento le paso esta contraseña al SDK?

**Comment by AndresRamos** [comment]
Este error se puede resolver modificando la configuracion de la empresa. A partir de una version reciente, no recuerdo exactamente cual exactamente, Comercial empezo a pedir la contrasena del certificado al querer dar de alta documentos de tipo CFDI.
No hay manera por el momento de asignar la contrasena del certificado para el alta de documentos, esto solo existe para la cancelacion.
Pare resolver este problema sigue estos pasos:
1. Abrir empresa de Comercial
2. En el menu principal ir a Configuracion
3. Ir a redefinir empresa
4. Ir a la pestana 8 "Facturacion electronica"
5. En Solicitar contrasena cada __ minutos asignar el valor "0"

Esto le dice a Comercial que ya no pida la contrasena del certificado para documentos de CFDI, solo al momento de timbrar,  por lo que el error en el SDK tambien se debe corregir.

**Comment by hdz1javier2** [comment]
Hola Andres, muchas gracias por el dato. Seguiré el proceso que me has
mandado.

saludos
