### ISSUE TITLE
Error al dar de alta direccion

### ISSUE THREAD

**Issue by ghost** [AndresRamos/Contpaqi#13]
cuando intento dar de alta una direccion con esta function fAltaDireccion(ref int aIdDireccion, ref tDireccion astDireccion) en Conpaq commercial, me aparece esta excepcion:
System.Runtime.InteropServices.SEHException[-2147467259]: Un componente externo produjo una excepción. -    en Contpaqi.Sdk.ComercialSdk.fLlenaRegistroDireccion(tDireccion& astDireccion, Int32 aEsAlta)
ya estuve verificando los parametros y el error continua, le puse un try/catch y me aparece el mismo codigo de error, aparte el struct de tDireccion no tiene el campo de cMunicipio, y en la base de datos si lo tiene

**Comment by AndresRamos** [comment]
Segun CONTPAQi en la version 6.0.2 de Comercial corrigieron la función, pero acabo de hacer pruebas en la version 6.1.1 y todavía sigue fallando. Ya no marca error pero no da de alta la dirección correctamente.

Si buscas dar de alta direcciones te recomiendo usar las funciones de bajo nivel por lo pronto.
Tengo un proyecto de ejemplos donde podrás ver como utilizar esas funciones.

En [EditarDireccionViewModel](https://github.com/AndresRamos/Contpaqi/blob/master/Contpaqi.Sdk.Ejemplos/ViewModels/Direcciones/EditarDireccionViewModel.cs) esta el ejemplo de como crear y editar direcciones. Este viewmodel manda a llamar el servicio [DireccionService](https://github.com/AndresRamos/Contpaqi/blob/master/Contpaqi.Sdk.Extras/Services/DireccionService.cs) donde podrás encontrar ejemplos de como funcionan las funciones de bajo nivel.

Para saber que datos debes proporcionar te puede servir de ejemplo la clase de ayuda [DireccionHelper](https://github.com/AndresRamos/Contpaqi/blob/master/Contpaqi.Sdk.Extras/Helpers/DireccionHelper.cs) que crea un diccionario de datos los cuales necesitas para dar de alta una dirección.

Por ejemplo: 

```csharp
// Crea el diccionario de datos
public static Dictionary<string, string> ToDatosDictionary(this Direccion direccion)
{
    var datosDireccion = new Dictionary<string, string>();
    datosDireccion.Add("CTIPOCATALOGO", ((int) direccion.TipoCatalogo).ToString());
    datosDireccion.Add("CTIPODIRECCION", ((int) direccion.TipoDireccion).ToString());
    datosDireccion.Add("CNOMBRECALLE", direccion.NombreCalle ?? "");
    datosDireccion.Add("CNUMEROEXTERIOR", direccion.NumeroExterior ?? "");
    datosDireccion.Add("CNUMEROINTERIOR", direccion.NumeroInterior ?? "");
    datosDireccion.Add("CCOLONIA", direccion.Colonia ?? "");
    datosDireccion.Add("CCODIGOPOSTAL", direccion.CodigoPostal ?? "");
    datosDireccion.Add("CTELEFONO1", direccion.Telefono1 ?? "");
    datosDireccion.Add("CTELEFONO2", direccion.Telefono2 ?? "");
    datosDireccion.Add("CTELEFONO3", direccion.Telefono3 ?? "");
    datosDireccion.Add("CTELEFONO4", direccion.Telefono4 ?? "");
    datosDireccion.Add("CEMAIL", direccion.Email ?? "");
    datosDireccion.Add("CDIRECCIONWEB", direccion.DireccionWeb ?? "");
    datosDireccion.Add("CCIUDAD", direccion.Ciudad ?? "");
    datosDireccion.Add("CESTADO", direccion.Estado ?? "");
    datosDireccion.Add("CPAIS", direccion.Pais ?? "");
    datosDireccion.Add("CTEXTOEXTRA", direccion.TextoExtra ?? "");
    datosDireccion.Add("CIDDIRECCION", direccion.Id.ToString());
    datosDireccion.Add("CIDCATALOGO", direccion.IdCatalogo.ToString());
    return datosDireccion;
}

// Crea la direccion utilizando funciones de bajo nivel
public int Crear(Dictionary<string, string> datosDireccion)
{
    _sdk.fInsertaDireccion().ToResultadoSdk(_sdk).ThrowIfError();
    SetDatosDireccion(datosDireccion);
    _sdk.fGuardaDireccion().ToResultadoSdk(_sdk).ThrowIfError();

    var idDireccionDato = new StringBuilder(12);
    _sdk.fLeeDatoDireccion("CIDDIRECCION", idDireccionDato, 12).ToResultadoSdk(_sdk).ThrowIfError();
    return int.Parse(idDireccionDato.ToString());
}

// Toma los datos del diccionario y los asigna a la direccion
private void SetDatosDireccion(Dictionary<string, string> datosDireccion)
{
    foreach (var dato in datosDireccion)
    {
        _sdk.fSetDatoDireccion(dato.Key, dato.Value);
    }
}
```

Espero esta informacion te sirva de ayudar. No olvides darle :star: al proyecto
