### ISSUE TITLE
Error uso SDK ComercialSdk.fSetFiltroDocumento

### ISSUE THREAD

**Issue by leutamo** [AndresRamos/Contpaqi#15]
Buenas tardes,
 
Tenemos un servidor de pruebas donde no logramos ejecutar correctamente el SDK, nos aparece un error Appcrash en la DLL CAC000.dll. Adjunto el enlace con la imagen

https://drive.google.com/file/d/1VWDm9yt5PkM5pLWBkRJ0yEPPDrvDPhBU/view?usp=sharing

Cabe precisar que la aplicación que tenemos logra solicitarnos el Client, apikey asi como el usuario y contraseña aceptando las credenciales. al intentar debugear nos aparece error en la línea ComercialSdk.fSetFiltroDocumento.

Tenemos otro servidor donde la misma aplicación se ejecuta sin problemas, podría indicarnos si es un error común?.

De antemano muchas gracias por la atención.

Saludos

**Comment by AndresRamos** [comment]
Tomando como referencia lo que me proporcionaste, podrías confirmarme lo siguiente:

1. Comercial esta instalado en la terminal que te marca el error?

1. Si estas abriendo la empresa antes de buscar los documentos?

1. Estas compilando tu aplicacion en x86?

1. Estas ejecutando Visual Studio en modo Administrador al momento de debugear?

[Contpaqi.Sdk.Ejemplos](https://github.com/AndresRamos/Contpaqi/tree/master/Contpaqi.Sdk.Ejemplos) es un proyecto de WPF con varios ejemplos de como utilizar el SDK. En el hay un modulo de facturas donde puedes listar las diferentes facturas por concepto y cliente utilizando esas mismas funciones. Puedes encontrar la funcionalidad de ese modulo en [ListadoFacturasViewModel](https://github.com/AndresRamos/Contpaqi/blob/master/Contpaqi.Sdk.Ejemplos/ViewModels/Facturas/ListadoFacturasViewModel.cs)

En [Contpaqi.Sdk.Extras](https://github.com/AndresRamos/Contpaqi/tree/master/Contpaqi.Sdk.Extras) podrás encontrar el repositorio [DocumentoRepository](https://github.com/AndresRamos/Contpaqi/blob/master/Contpaqi.Sdk.Extras/Repositories/DocumentoRepository.cs) que tiene la funcion `TraerPorRangoFechaYCodigoConceptoYCodigoClienteProveedor` que implementa la función `fSetFiltroDocumento` del SDK.

Te recomiendo que descargues este repositorio y ejecutes el proyecto de ejemplos en la computadora que te marca el error. Si se ejecuta correctamente puede ser que haya algo mal declarado o estructurado en tu codigo. Si te marca error tendríamos que analizarlo mas a detalle. Podría se un error de permisos de las carpetas, configuración del servidor, o licenciamiento. Ya errores menos comunes.

**Comment by leutamo** [comment]
Hola Andres, muchas gracias por responder. te confirmo las preguntas que me realizaste:

_Comercial esta instalado en la terminal que te marca el error?_
**Sí esta instalado.**(adjunto pantalla)

_Si estas abriendo la empresa antes de buscar los documentos?_
**Si correcto, (adjunto una pantalla).**

_Estas compilando tu aplicacion en x86?_
Al inicio lo estuve haciendo en AnyCpu, luego intente también con x86 pero me daba el mismo error.

_Estas ejecutando Visual Studio en modo Administrador al momento de debugear?_
Anteriormente no, pero luego intente como administrador y me dio el mismo error.

Logré descargar su proyecto y logre compilarlo y ejecutarlo sin problemas, no logre acceder por que aún no logro obtener la contraseña del Supervisor, pero lo voy a solicitar cuanto antes para poder probar las llamadas que haces.

Por otro lado me percaté que el servidor de pruebas que te comenté en la carpeta x86/Compacw/AdminPAQ no se visualizan archivos es decir no veo ningún DLL(solo 53 elementos), en cambio en la misma carpeta pero del servidor que tengo operativo logro visualizar todos los DLL incluso el archivo CAC000.dll(+250 elementos). que no existe en el server de prueba. Crees que sea buena idea la reinstalación de todos los paquetes?

Adjunto las pantallas de ambos servidores a ver si me puedes dar alguna pista para identificar algún error que no logro visualizar,

https://drive.google.com/drive/folders/1i1DtKVbKYBvo5KPGgFCTwyr4hHCSr8SQ?usp=sharing

de antemano muchas gracias por su ayuda, espero mañana realizar la última prueba que me has recomendado.

Saludos!!

**Comment by AndresRamos** [comment]
Estas tratando de consumir el SDK de Comercial o de Adminpaq?

Adminpaq y Comercial son dos diferentes aplicaciones por lo que dependiendo del sistema que quieres utilizar debe usar el SDK apropiado. 

Podrías especificarme con cual sistema o SDK estas tratando de trabajar?

**Comment by leutamo** [comment]
Hola, buen día Andres.

Estoy intentando consumir el SDK de Comercial, te adjunto pantalla para confirmar

https://drive.google.com/file/d/1ma13gvyDw0OLgi7lGfAQFbG44TjggdSZ/view?usp=sharing

Y también te adjunto pantalla donde la aplicación ya no avanza, primero si me logra solicitar la empresa, el apikey etc y abre la empresa el problema es cuando uso ese filtro que ahora observaras:

https://drive.google.com/file/d/1APY_7fDjpi1M3SuRYTesW9BcymDkHBiq/view?usp=sharing

Gracias!!

**Comment by AndresRamos** [comment]
Sin poder ver el codigo va a ser un poco complicado encontrar una solución.

Por ejemplo: cuales son los valores que estas mandando? Y cuando dices que si funciona en el servidor de producción te refieres que ahi si se ejecuta correctamente y te trae el listado de documentos?

Por lo pronto te recomiendo que hagas lo siguiente. Ejecuta el proyecto de ejemplos para ver si también te marca el error.
1. Inicia sesión
1. Abre empresa
1. Ve al menu de Movimientos y dale a  la opcion facturas.
1. Busca facturas utilizando la función.

Dejame saber si te marca algún error en alguno de los pasos.

**Comment by leutamo** [comment]
Hola Andres buenas tardes,

Los valores que mando son tal cual los solicita el sdk el formato fecha pero como string como lo leí en la documentación, nosotros procesamos un CSV que contiene estos campos. Cuando indico que en producción funciona bien me refiero a que tenemos un servidor actual en producción y la misma aplicación funciona sin problemas, en el otro servidor de "pruebas", aparecen los errores que te adjunté.

Por otro lado logré ejecutar tu proyecto el de ejemplos con el usuario que nos proporcionaron. y solo se logra realizar el proceso hasta el número 3, te adjunto pantallas:

**1. Iniciando sesión - Ok**
https://drive.google.com/file/d/1SBzMgUhbjTqiNbKYB6181cLZmVSXZigC/view?usp=sharing

**2. Abre empresa - OK**
https://drive.google.com/file/d/1c4zarAf3gd5v3Kp5hAapIO1O6LAmnIfx/view?usp=sharing

**3.Ve al menu de Movimientos y dale a la opcion facturas - Error,** en esta parte al darle click se queda la aplicación como congelada. Lo he dejado unos 10 hasta 20 minutos y no responde no da error pero tampoco deja interactuar con el UI.

https://drive.google.com/file/d/1bPrHJFvhep-k6RhRpgqvI5JvfDxMG8UE/view?usp=sharing

Intenté debugear pero se queda aquí, en window.show():

https://drive.google.com/file/d/1OWjYo8CrXCcAbKbDftA9zrXCgeCiyrwQ/view?usp=sharing

En ninguno de los pasos me da error solo se queda sin responder. Con nuestra aplicación que es de consola al parecer igual, nos solicita el usuario password y abre la empresa pero bueno se queda en los otros errores que te he contado anteriormente.

Te ha pasado esto antes?.

Muchas gracias!

**Comment by AndresRamos** [comment]
Cuando abres la ventana de listado de facturas se manda llamar el comand `InicializarCommand` que manda a llamar la función `Inicializar()` que manda a llamar las funciones `CargarConceptos()` y `CargarClientes()`. Si no se abrió la ventana y pero no te marco error quiere decir que todavía no terminaba de cargar esos catalogos. Las búsquedas con el SDK pueden ser lentas dependiendo de cuantos registros tengas.

Cuantos clientes tienes? Si te vas a la opcion de Catalogos => Clientes y le das buscar clientes cuanto tarda?

Si abres el sistema de Comercial, me refiero a la aplicacion completa, si puede entrar y listar catalogos y documentos?

**Comment by leutamo** [comment]
Hola Andres, 

Tenemos unos 17.534 registros, con la aplicación de ejemplo me cargan unos 10 clientes y luego aparecen un par de errores. Los adjunto:

https://drive.google.com/file/d/1HFpFxt1tRqNGWSmPTszQPZIGfDjylBKl/view?usp=sharing
https://drive.google.com/file/d/1ZBBqQZtYQ79rg9uBVcUJUfK96-_VlVIn/view?usp=sharing

Ahora he realizado la consulta con el sistema comercial y hay aprox unos 17.534 registros. cuando hago la consulta de clientes tardó aprox 10 a 15 segundos. Te adjunto pantalla.

https://drive.google.com/file/d/1WQtEcx8_qTcUI89RPsrzTiq6VCKMCgHU/view?usp=sharing
https://drive.google.com/file/d/1pO1MKuWsMH4LkKxmlsJ0Se7BX9C9Xm39/view?usp=sharing

Por otro lado con la aplicación de ejemplo al intentar cargar las facturas se sigue quedando en freeze y no responde el UI lo deje como 30 minutos pero sin respuesta. Si logro acceder a catalogos-> Unidades, me aparece la ventana para buscar y se busca sin problemas, pero si intento buscar por ejemplo catalogos-> documentos no abre nisiquiera la interfaz y se queda congelada la aplicación sin mostrar nada.

De momento voy a utilizar el otro servidor hasta detectar el problema en este de prueba, muchas gracias por tu apoyo.

Saludos!!

**Comment by AndresRamos** [comment]
Acabo de subir un commit nuevo al repositorio que resuelve el error que te marca al querer listar los clientes utilizando el proyecto de ejemplos.
Este proceso es mas tardado ya que si te metes al codigo el repositorio carga varias columnas y objetos relacionados que hace que tarde un poco mas la búsqueda. Puedes volver a intentar listar los clientes?

**Comment by leutamo** [comment]
Hola Andres, acabo de descargar tu commit y efectivamente el de clientes ahora ya pasa de las 10 búsquedas sin problemas.

Aún sigue el problema de las facturas, que no muestra interfaz. Y justamente quiero verificar allí esta consulta fSetFiltroDocumento. Ya que el programa que tengo logra acceder a la empresa, la abre pero justo en esa llamada me da error. y con el proyecto que me enviaste aún no logro probar esa función.

Consulta, necesito tener instalado el \AdminPAQ para que funcione?. Ya que con los errores que estuve revisando me pide DLLs que se encuentran en dicha carpeta C:\Program Files (x86)\Compacw\AdminPAQ y que en mi servidor de pruebas no existen pero en el de Producción sí.

muchas gracias por tu apoyo.

Saludos!!

**Comment by AndresRamos** [comment]
No necesitas tener instalado Adminpaq para trabajar con Comercial o con su SDK ya que son dos aplicaciones totalmente diferentes y sus SDK también funcionan diferente. La razon por la que los nombres son similares fue por que en su momento cuando hicieron el cambio de Adminpaq a Comercial quisieron mantener la mayor compatibilidad posible y por eso puedes encontrar similitudes en los nombres de las dll.

La razon por la que pudiera estarse tardando en abrir la ventana de listado de facturas puede ser por que tu catalogo es muy grande, y como el SDK no se puede correr asíncrono, esto causa que el GUI se queda trabado o pensando. Podrías poner un breakpoint cada cierto tiempo dentro del loop de búsqueda de los repositorios de clientes para validar que el SDK todavía siga trabajando. Esta es una de las desventajas en mi opinion del SDK por lo que yo en mis aplicaciones hago las consultas directamente en SQL. Tambien tengo un repositorio para hacer eso si te interesa.

Necesitamos que la aplicacion de ejemplos marque un error para saber por donde va. Si es error del SDK o de la computadora donde lo estas corriendo.

Podrías modificar el codigo para que no busque los catalogos al iniciar la ventana. Puedes comentar lo siguiente en la funcion `Inicializar()`:

```csharp
public void Inicializar()
{
    CargarConceptos();
    //CargarClientes(); Asi ya no busca el catalogo de clientes
}
```

Tambien modifica la función `BuscarConFiltroAsync()` y asigna el codigo del cliente directamente y asi haces la prueba.

Por ejemplo en la funcion `BuscarConFiltroAsync()` elimina los siguiente:

``` csharp
var documentos = ClienteSeleccionado.Id == 0
    ? _documentoRepository.TraerPorRangoFechaYCodigoConceptoYCodigoClienteProveedor(FechaInicio, FechaFin, ConceptoSeleccionado.Codigo, Clientes.Where(c => c.Id != 0).Select(c => c.Codigo).ToList())
    : _documentoRepository.TraerPorRangoFechaYCodigoConceptoYCodigoClienteProveedor(FechaInicio, FechaFin, ConceptoSeleccionado.Codigo, ClienteSeleccionado.Codigo);
```
Remplazalo por algo asi:
```csharp
_documentoRepository.TraerPorRangoFechaYCodigoConceptoYCodigoClienteProveedor(FechaInicio, FechaFin, ConceptoSeleccionado.Codigo, "CodigoCliente"); // donde "CodigoCliente" es un codigo de clientes valido que si existe en Comercial
```

Intentalo y dejame saber el resultado de las pruebas.

**Comment by leutamo** [comment]
Hola Andres, intenté lo que que me indicaste. y de nuevo me da error de compilación.

Una consulta, es mejor instalar el SDK manualmente o desde el Nuget. Yo intenté de ambas formas sin éxito.

Y que versión utilizas para trabajar la 1.0.6 o la v 2?. El proyecto actual que existe veo que hace una llamada al Contpaqi.Sdk.Extras.Ayudantes | pero esto no lo he visto en tu proyecto de ejemplo.

En cualquiera de los casos crees que si coordino una videollamada me puedas apoyar solo unos minutos por favor? y te muestro en línea el error.

Muchas gracias!!
