### ISSUE TITLE
Proyecto en web no se conecta

### ISSUE THREAD

**Issue by cholodelinea** [AndresRamos/Contpaqi#16]
Buenos dias, tengo na aplicacion en consola con el SDK y me funciona correctamente. ahora se esta migrando a web en un proyecto en MVC y cuando intenta conectarse al contpaq me regresa un error que dice "proceso cancelado" y los metodos de fSetNombrePAQ y fInicializaSDK lanzan una excepcion, antes me decia que el formato era incorrecto hasta que en el IIS le configure que utilizara aplicaciones de 32 bits, utilize los mismos metodos de conexion y parametros que utilizo en el proyecto de consola que es el que si funciona, pero ya en MVC parece que no logra inicializar

**Comment by pstoneTI** [comment]
Buen día, no se si hayas revisado ya este tema, en lo personal no he manejado el SDK desde IIS pero en los foros de Contpaqi compartieron esta guía (No tiene autor así no puedo citar el crédito) :

[https://drive.google.com/file/d/1CpRZgnSI8LknqTU7fK7h3bPjD9lzBPxt/view?usp=sharing](url)

Puedes probar esas configuraciones para ver si tu error se resuelve.

Saludos

**Comment by cholodelinea** [comment]
> Buen día, no se si hayas revisado ya este tema, en lo personal no he manejado el SDK desde IIS pero en los foros de Contpaqi compartieron esta guía (No tiene autor así no puedo citar el crédito) :
> 
> [https://drive.google.com/file/d/1CpRZgnSI8LknqTU7fK7h3bPjD9lzBPxt/view?usp=sharing](url)
> 
> Puedes probar esas configuraciones para ver si tu error se resuelve.
> 
> Saludos

Muchisimas gracias, el documento trae varias configuraciones que no habia contemplado, si llego a tener éxito lo pondré con un reply en este post, de nuevo gracias y Saludos
