### ISSUE TITLE
Error en las clases ServicioDocumentoComercial y ServicioClienteProveedorComercial

### ISSUE THREAD

**Issue by suzuma** [AndresRamos/Contpaqi#2]

**Comment by AndresRamos** [comment]
Que tipo de error te marco? 
Vi que editaste tu comentario. Se pudo resolver el problema?
Podrias tambien especificar cual SDK estás utilizando? Adminpaq o Comercial?

**Comment by suzuma** [comment]
Estaba viendo el codigo de Adminpaq. requiero consultar el inventario de determinados productos y fechas de caducidad. Revisando la documentacion del SDK no logre tener acceso a esos datos. Tu has consultado por medio de OLEDB driver?

**Comment by AndresRamos** [comment]
Dame unos días para averiguar si es posible consultar esos datos usando el SDK de Adminpaq.
Para consultar directamente las bases de datos de Adminpaq necesitas usar el OLEDB de Fox Pro ya que Adminpaq usa ese tipo de bases de datos.
Si he podido mapear las bases de datos de Adminpaq usando Entity Framework pero no están incluidas en esta librería.

**Comment by faraonchis** [comment]
Que tal. ¿No tienes nada para comentar sobre como agregar los xmls directamente a las BBDD?

**Comment by AndresRamos** [comment]
No es posible hacer eso mediante el SDK.
