### ISSUE TITLE
Compatibilidad correcta con Windows 10

### ISSUE THREAD

**Issue by elialejandro** [AndresRamos/Contpaqi#3]
https://github.com/AndresRamos/Contpaqi/blob/57c5aef53d901a6ce5468a3e38fe9175c1d5539b/Contpaqi.Sdk.Extras/Contpaqi.Sdk.Extras.csproj#L12

Hola yo he trabajado con el SDK y a mi me funciona bien con Windows 10 y sin elevar privilegios al usar Netframework 4.0 para construir la aplicación, también los ensamblados deben de hacerse para x86

**Comment by AndresRamos** [comment]
Hola Alejandro,

En cuanto al framework yo lo tengo compilado en 4.5 pero como tu lo mencionas tambien lo puedes compilar en .net framework 4.0. De hecho creo que se puede compilar hasta .net framework 2.0.

Debo probar lo que mencionas de utilizar el SDK sin que se corra como "Administrador" ya que a mi y como lo mencionan en los foros, siempre te marca error de memoria protegida si no elevas los permisos. Y sea con Adminpaq o Comercial.

Lo que te quería preguntar es lo que mencionas de compilar el SDK en x86, Dices que es obligatorio? Siempre lo he compilado como Any CPU y nunca eh tenido problemas con esa configuración. Las aplicaciones si las que consumen el SDK si las compiló en x86 pero el la libreria en sí no.

**Comment by elialejandro** [comment]
Tengo entendido que el SDK está compilado en x86, por lógica la aplicación que lo con suma debe ser en x86. De hecho aunque funcione con Any CPU no hay mucha ventaja en compilar con Any CPU. También he probado compilar la extensión con Any CPU no veo ningún inconveniente.

En la configuración de mi aplicación tengo x86 para hacer el release y al ejecutar solo compatibilidad con Windows 7 y sin ejecutar como administrador, la escribí con NetFramework 4.5 y todo funcionó correctamente.

Felicidades es grandioso el esfuerzo que haz realizado para tener lista y disponible la extensión.

**Comment by icebergdelphi** [comment]
Hola buenos dias, que archivos de tu proyecto que me parece magnifico debo de usar para poder facturar?, es decir tenemos un modulo ya hecho de pedidos en C# con SQL, ahora queremos mandar esos datos de pedidos al AdminPAQ y que desde ahi se facture todo. muchas gracias,

**Comment by AndresRamos** [comment]
Si quieres interactuar con (Adminpaq, Comercial, o Factura Electronica) necesitas hacer uso del SDK. 
La librería **Contpaqi.Sdk** contiene todas las funciones proporcionadas por Contpaq.

**Comment by icebergdelphi** [comment]
Muchas gracias Andres, el ContaPaq solo lo utilizariamos para mandarle los datos y facturar, pero no se si es mas conveniente usar un SDK externo y que desde nuestra aplicacion de una vez se facture sin enviar al Contapaq.

**Comment by AndresRamos** [comment]
Necesito tomarme el tiempo de agregar documentacion a mi libreria.
Facturar en Adminpaq utilizando el SDK es muy sencillo. 
Cuando dices pasar la informacion me imagino que te refieres a crear los documentos (facturas). Una vez creada la factura puedes utilizar una función que se llama fEmitirDocumento que timbra la factura.

**Comment by icebergdelphi** [comment]
Muchas gracias, mira mas que nada me gustaria saber que elementos de la libreria tomara para poder desde mi Sistema mandarle los datos al AdminPaq y que facture, es decir en mi sistema tengo una ventana de pedidos que es la clasica venta (Master y detalles) esos datos los queremos mandar al Adminpaq y que se facture lo que yo le envie desde mi sistema, pero no se exactamente que funcion o funciones de la libreria tomar, no se si tienes como una guia rapida o que me digas cuales tomo... ya que como tu bien dices no hay aun documentacion se me hace un poco confuso, muchas gracias.

**Comment by AndresRamos** [comment]
Mandame un mensaje a mi correo andres@arsoft.net y te mando un ejemplo.

**Comment by icebergdelphi** [comment]
Ok gracias nuy amable ya te lo estare enviando hoy,

**Comment by icebergdelphi** [comment]
Hola amigo buen día te mande un Email , me comentabas que me enviarias un ejemplo de como puedo mandar los datos de mis pedidos desarollado por nosotros al adminpaq y que estos los facture, que funcion debemos de usar para los datos del detalle de pedidos? muchas gracias,
