### ISSUE TITLE
No se puede cargar el archivo DLL 'MGWServicios.dll'

### ISSUE THREAD

**Issue by alcaraz73** [AndresRamos/Contpaqi#6]
Hola Andrés,

estoy intentando iniciar con el SDK, pero el ejecutar fInicializaSDK me sale el error que menciono.

¿Es necesario agregar alguna referencia o algo similar?

Gracias de antemano.

**Comment by AndresRamos** [comment]
Revisaste la documentación en [Iniciar SDK](https://github.com/AndresRamos/Contpaqi/wiki/Iniciar-SDK)?
Los requisitos para poder inicializar el SDK son los siguientes:

1. Tener instalado el sistema en la maquina donde vas a ejecutar el desarrollo. En este caso debes tener instalado CONTPAQi Comercial.
2. Ejecutar el desarrollo en modo Administrador.

Ejemplo: 
```csharp
public const string NombreLlaveRegistroComercial = @"SOFTWARE\\Computación en Acción, SA CV\\CONTPAQ I COMERCIAL";
public const string NombrePaqComercial = "CONTPAQ I COMERCIAL";

public int IniciarSdkComercial()
{
    var keySistema = Registry.LocalMachine.OpenSubKey(NombreLlaveRegistroComercial);
    var lEntrada = keySistema.GetValue("DirectorioBase");
    Directory.SetCurrentDirectory(lEntrada.ToString());
    return ComercialSdk.fSetNombrePAQ(NombrePaqComercial);
}
```

**Comment by alcaraz73** [comment]
Gracias Andres, ¿dónde puedo descargar la documentación?  Originalmente lo descargue con el Package Manager.

Saludos.

**Comment by alcaraz73** [comment]
Parece que mi problema con VS 2017 es que no se estaba ejecutando como Administrador, pero ya parece estar resuleto.

Ahora obtengo un mensaje de System.BadImageFormatException.  Ya intente Any CPU, x86 y x64 y no lo soluciono.

¿Tendrás idea de esto?  

Gracias de antemano.

**Comment by AndresRamos** [comment]
No viene documentación a través de Nuget. Pero aquí en Github tengo agregados documentos de la documentación del SDK que provee CONTPAQi. Te anexo la liga a los [Documentos](https://github.com/AndresRamos/Contpaqi/tree/master/Documentos)

**Comment by Syscore1** [comment]
Que tal Andrés.

Sabes si ya es posible realizar transformaciones mediante SDK?

Saludos.

**Comment by AndresRamos** [comment]
Todavia no es posible crear transformaciones utilizando el SDK.

**Comment by nasariogarti** [comment]
Para integrar el SDK en una aplicación web, se puede aplicar de la misma forma, estoy trabajando con CONTAQ Comercial
