### ISSUE TITLE
Imprevisto con contpaq i contabilidad

### ISSUE THREAD

**Issue by arnulfoaqm** [AndresRamos/Contpaqi#7]
Hola Andres, la libreria esta genial! logré crear el proyecto y funciona perfectamente en mi entorno de desarrollo y aún en el entorno de producción. Solo tengo el inconveniente de que en el entorno de producción el contpaq i comercial, esta "conectado" o integrado con el contpaq i contabilidad.  Y lo que sucede es que cuando carga la libreria y abre la empresa en la app que desarrollé, aparecé el inicio de sesión de cti CONTABILIDAD.  Entonces cada vez que se corre el proceso desde la APP hay que introducirle la clave de cti CONTABILIDAD, una y otra vez porque sino le introduzco dicho password, el proceso no continua.

Entonces la app que desarrollé corre un sondeo cada 10 minutos y lo hace en el servidor, lo que implica que el contador tiene que abrir el site, y poner dicho password cada 10 minutos para que la app que desarrolle pueda funcionar y pues como verás no es nada funcional.

Me interesa saber si has pasado por este escenario y como resolverlo, 

Te agradezco de antemano tus comentarios

aaz.

**Comment by AndresRamos** [comment]
Existe una función exactamente para este caso.
Después de iniciar session a Comercial manda a llamar la función **fInicioSesionSDKCONTPAQi**.
```csharp
[DllImport("MGWServicios.dll", EntryPoint = "fInicioSesionSDKCONTPAQi")]
public static extern void fInicioSesionSDKCONTPAQi(string aUsuario, string aContrasenia);

sdk.fInicioSesionSDKCONTPAQi("SUPERVISOR", "");
```

**Comment by carloschavero** [comment]
Buenas noches:

Me podrían proporcionar algún ejemplo donde se aplique una factura, nota de crédito y comprobante de pago y cancelación de los mismos, por favor, gracias.

Saludos.

**Comment by AndresRamos** [comment]
@carloschavero tienes acceso a los foros de CONTPAQi? Ahi podras encontrar varios ejemplos de lo que buscas.
