### ISSUE TITLE
Timbrar XML

### ISSUE THREAD

**Issue by M3rino** [AndresRamos/Contpaqi#8]
Buen día,  voy empezando con el SDK 
estoy tratando de timbrar masivamente XML generados por mi sistema

quiero usar la facilidad que de Comercial Pro al tener timbrado ilimitado, lo  haría con un PAC, pero quiero aprovechar la licencia que ya se tiene.

estoy tratando de averiguar como funciona  fTimbraXML() pero de entrada me arroja el sig. error.
"{"No se puede encontrar el punto de entrada denominado 'fTimbraXML' en el archivo DLL 'MGWServicios.dll'.":""}"

que recomendaciones me puedes dar al respecto del SDK (buenas practicas) ya que casi no encuentro documentación.  y no tengo acceso a los foros de Contpaq,
 
De antemano muchas gracias por la documentación, haz hecho un buen trabajo.

**Comment by AndresRamos** [comment]
El SDK no es compatible con Comercial PRO. Te referias talvez a Comercial Premium?

En dado caso, las funciones para timbrar XMLs solo funcionan con el sistema de Adminpaq y Factura Electronica, y necesitas tener una licencia de 5 usuarios.

En este repositorio (https://github.com/AndresRamos/Contpaqi/tree/master/Documentos) podras encontrar documentacion de los SDKs y las bases de datos de Adminpaq y Comercial.

**Comment by M3rino** [comment]
Tienes razón, me refería a Comercial Premium.
gracias por la información

**Comment by AndresRamos** [comment]
Si quieres timbrar facturas con Comercial Premium necesitas dar de alta el documento en Comercial con la funcion **fAltaDocumento** y luego mandarlo a timbrar con la funcion **fEmitirDocumento**.

Para timbrar XMLs directamete solamente es posible con Adminpaq y Factura Electronica.

**Comment by M3rino** [comment]
duda:
porque cuando quiero iniciar el SDK con Adminpaq o Factura Electrónica me sale este error:
No se puede cargar el archivo DLL 'MGW_SDK.dll': No se puede encontrar el módulo especificado. (Excepción de HRESULT: 0x8007007E) 

el SDK que tengo instalado es el 11.5.2
Adminpaq es 11.3.0
Comercial 4.5.1  //=> con este no tengo problemas

private const string NombreLlaveRegistroAdminpaq = @"SOFTWARE\\Computación en Acción, SA CV\\AdminPAQ";


public int InicializarSDKAdminpaq()
{
    var keySistema = Registry.LocalMachine.OpenSubKey(NombreLlaveRegistroAdminpaq);
    var lEntrada = keySistema.GetValue("DirectorioBase");
    Directory.SetCurrentDirectory(lEntrada.ToString());
    return AdminpaqSdk.fSetNombrePAQ("AdminPAQ");  //==> Aquí obtengo el error mencionado 
}

codigo extraido de [https://github.com/AndresRamos/Contpaqi/wiki/Iniciar-SDK](url)
Saludos!

**Comment by M3rino** [comment]
Despues de algunos días ya logré resolver el error de inicio de del SDK con el AdminPAQ

ahora si estoy tratando de timbrar un XML generado por fuera. 
y obtengo el error -1 "plataforma" dice el mensaje de Error.

antes de usar fTimbraXML estoy inicializando el servidor de licencias fInicializaLicenseInfo ==> este no manda ningun error.

sabrás que estoy omitiendo?
agradezco mucho tu orientación. Saludos!

**Comment by AndresRamos** [comment]
Es complicado saber la razon si no puedo ver tu codigo. Podrias compartirme tu ejemplo?

**Comment by marcos-moreno** [comment]
Buen día, ya estoy trabajando con esta libreria y sus funcionalidades son muy buenas, ya consegui la mayor parte de requerimientos necesarios de mi aplicación, solo que no logro crear una orden de venta, me podrías orientar sobre  esa parte?

**Comment by AndresRamos** [comment]
@marcos-moreno necesitas un ejemplo de como crear un documento? Si es asi hoy ya me programe para generar unos ejemplos en el Wiki. Cuando los tenga te dejo saber o revisa el Wiki manana.

**Comment by marcos-moreno** [comment]
Correcto @AndresRamos ...
Muchas gracias!

**Comment by tekcelerdev** [comment]
Hola @AndresRamos 
Tengo un proyecto en Visual Studio y uso el SDK para crear documentos en Contpaqi comercial y timbrarlos. Puedo crear los documentos sin problemas, inclusive creo nuevos produrctos y clientes...  pero justo en la función ComercialSdk.fEmitirDocumento() recibo el siguiente error:
"System.AccessViolationException: 'Intento de leer o escribir en la memoria protegida. A menudo, esto indica que hay otra memoria dañada.'"

He compilado mi proyecto para x86 pero sigo con el mismo error... ¿alguna idea que me puedas dar por favor? Muchas gracias.

**Comment by albertojimpala** [comment]
@M3rino como resolviste el problema de.plataforma en el timbrado ?

**Comment by gabriellrios03** [comment]
@albertojimpala  El error de -1 Error de Plataforma se debe en ocasiones a que el método que estas utilizando del SDK requiere de una licencia de N# Usuarios, asegúrate de tener los usuarios necesarios para el método que estas utilizando, ademas como sugerencia prueba abriendo el sistema por completo (Con la empresa que estas utilizando y timbra un Documento *Claro si esto es posible) eh tenido ese error y es la forma en la que eh logrado solucionar el mismo.
