### ISSUE TITLE
Bancos SDK

### ISSUE THREAD

**Issue by M3rino** [AndresRamos/Contpaqi#9]
Buen día colegas,
¿Tendrán documentación referente o algún ejemplo para crear Pólizas de Ingreso y/o Egreso en  Bancos por medio del SDK()?

de antemano agradezco el apoyo. 
Saludos!

**Comment by AndresRamos** [comment]
Tengo el proyecto [Contpaqi.Sdk.Contabilidad](https://github.com/AndresRamos/Contpaqi.Sdk.Contabilidad) donde podrás encontrar ejemplos del SDK de Contabilidad. Es un proyecto nuevo por lo que todavía no agrego un ejemplo para la generación de pólizas, pero muy pronto estaré agregando esos ejemplos.
